name: Deploy Bot

on:
  push:
    branches: [ main ]

jobs:
  run-bot:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      CLICKBANK_NICKNAME: ${{ secrets.CLICKBANK_NICKNAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python Main.py
